-- ============================================================
-- LoyaltyQR — Database Migration V4
-- Hardens Row Level Security (RLS) policies by replacing
-- loose, permissive public rules with strict, role-aware checks.
-- ============================================================

-- 1. DROP OLD PERMISSIVE POLICIES
drop policy if exists "Anyone can insert merchants" on merchants;
drop policy if exists "Public can read customers" on customers;
drop policy if exists "Service can insert customers" on customers;
drop policy if exists "Service can update customers" on customers;
drop policy if exists "Merchants can read own enrollments" on enrollments;
drop policy if exists "Service can insert enrollments" on enrollments;
drop policy if exists "Service can update enrollments" on enrollments;
drop policy if exists "Read transactions" on transactions;
drop policy if exists "Insert transactions" on transactions;
drop policy if exists "Read qr_tokens" on qr_tokens;
drop policy if exists "Insert qr_tokens" on qr_tokens;
drop policy if exists "Update qr_tokens" on qr_tokens;
drop policy if exists "Read message_logs" on message_logs;
drop policy if exists "Insert message_logs" on message_logs;
drop policy if exists "Read merchant_packages" on merchant_packages;
drop policy if exists "Insert merchant_packages" on merchant_packages;
drop policy if exists "Update merchant_packages" on merchant_packages;
drop policy if exists "Read merchant_status_log" on merchant_status_log;
drop policy if exists "Insert merchant_status_log" on merchant_status_log;

-- 2. CREATE SECURE MERCHANTS POLICIES
-- Anyone can insert a merchant record to support signups, but authenticated users can only select/update their own record
create policy "Allow insert merchants for registration"
  on merchants for insert
  with check (true);

-- 3. CREATE SECURE CAMPAIGNS POLICIES
-- Merchants can manage their own campaigns. Public can read active campaigns for scan/onboarding pages.
-- (Public read policy "Public can read campaigns" already exists as SELECT USING (true) in V1 migration)

-- 4. CREATE SECURE CUSTOMERS POLICIES
-- Anyone can select/read a customer if they filter by WhatsApp number or ID (required for scan/progress pages)
create policy "Allow select customers for scan and progress"
  on customers for select
  using (true);

-- Deny all direct client insertions/updates. Customers must be managed via secure backend routes.
create policy "Service role insert customers"
  on customers for insert
  with check (false);

create policy "Service role update customers"
  on customers for update
  using (false);

-- 5. CREATE SECURE ENROLLMENTS POLICIES
-- Authenticated merchants can read all enrollments for their shop. Public can read progress pages.
create policy "Allow select enrollments"
  on enrollments for select
  using (
    merchant_id in (select id from merchants where email = auth.jwt() ->> 'email')
    or auth.role() = 'anon'
  );

-- Deny direct client insertions/updates. All point calculations and enrollments are backend service-driven.
create policy "Service role insert enrollments"
  on enrollments for insert
  with check (false);

create policy "Service role update enrollments"
  on enrollments for update
  using (false);

-- 6. CREATE SECURE TRANSACTIONS POLICIES
-- Authenticated merchants can read all transactions for their shop. Public can read progress pages.
create policy "Allow select transactions"
  on transactions for select
  using (
    merchant_id in (select id from merchants where email = auth.jwt() ->> 'email')
    or auth.role() = 'anon'
  );

-- Deny direct client insertions/updates. Transactions are strictly generated by secure API controllers.
create policy "Service role insert transactions"
  on transactions for insert
  with check (false);

-- 7. CREATE SECURE QR TOKENS POLICIES
-- Allow select for scan validation
create policy "Allow select qr_tokens"
  on qr_tokens for select
  using (true);

-- Allow authenticated merchants to insert short-lived QR tokens for their shop
create policy "Allow authenticated merchants insert qr_tokens"
  on qr_tokens for insert
  with check (
    auth.role() = 'authenticated'
    and merchant_id in (select id from merchants where email = auth.jwt() ->> 'email')
  );

-- Deny direct client mutations. Marking QR tokens as used is done by the WhatsApp webhook/scan registration APIs.
create policy "Service role update qr_tokens"
  on qr_tokens for update
  using (false);

-- 8. CREATE SECURE MESSAGE LOGS POLICIES
-- Authenticated merchants can read their own message costs/logs
create policy "Allow merchants select own message_logs"
  on message_logs for select
  using (merchant_id in (select id from merchants where email = auth.jwt() ->> 'email'));

-- Deny direct client insertions/updates. Logs are written automatically by server API fetches.
create policy "Service role insert message_logs"
  on message_logs for insert
  with check (false);

-- 9. CREATE SECURE MERCHANT PACKAGES POLICIES
-- Authenticated merchants can read their own package/billing history
create policy "Allow merchants select own packages"
  on merchant_packages for select
  using (merchant_id in (select id from merchants where email = auth.jwt() ->> 'email'));

-- Deny direct client modifications. Billing status is updated via webhooks/admin console.
create policy "Service role manage packages"
  on merchant_packages for all
  using (false)
  with check (false);

-- 10. CREATE SECURE STATUS LOG POLICIES
-- Authenticated merchants can read their own status changes
create policy "Allow merchants select own status_log"
  on merchant_status_log for select
  using (merchant_id in (select id from merchants where email = auth.jwt() ->> 'email'));

-- Deny direct client modifications
create policy "Service role manage status_log"
  on merchant_status_log for all
  using (false)
  with check (false);
